const refs = {
  R1:  { id: "R1",  authors: "Zmora N, et al.",          year: 2018, journal: "Cell",                            title: "Personalized gut mucosal colonization resistance to empiric probiotics is associated with unique host and microbiome features",           doi: "10.1016/j.cell.2018.08.041",          if: "64.5", q: "Q1" },
  R2:  { id: "R2",  authors: "Zhao L, et al.",           year: 2018, journal: "Science",                          title: "Gut bacteria selectively promoted by dietary fibers alleviate type 2 diabetes",                                                          doi: "10.1126/science.aao5774",              if: "56.9", q: "Q1" },
  R3:  { id: "R3",  authors: "Plovier H, et al.",        year: 2017, journal: "Nature Medicine",                  title: "A purified membrane protein from Akkermansia muciniphila or the pasteurized bacterium improves metabolism in obese and diabetic mice",   doi: "10.1038/nm.4236",                     if: "82.9", q: "Q1" },
  R4:  { id: "R4",  authors: "Turnbaugh PJ, et al.",     year: 2006, journal: "Nature",                           title: "An obesity-associated gut microbiome with increased capacity for energy harvest",                                                         doi: "10.1038/nature05414",                  if: "69.5", q: "Q1" },
  R5:  { id: "R5",  authors: "Ridaura VK, et al.",       year: 2013, journal: "Science",                          title: "Gut microbiota from twins discordant for obesity modulate metabolism in mice",                                                             doi: "10.1126/science.1241214",              if: "56.9", q: "Q1" },
  R6:  { id: "R6",  authors: "Le Chatelier E, et al.",   year: 2013, journal: "Nature",                           title: "Richness of human gut microbiome correlates with metabolic markers",                                                                        doi: "10.1038/nature12506",                  if: "69.5", q: "Q1" },
  R7:  { id: "R7",  authors: "Sonnenburg JL & Backhed F",year: 2016, journal: "Nature",                           title: "Diet-microbiota interactions as moderators of human metabolism",                                                                           doi: "10.1038/nature18846",                  if: "69.5", q: "Q1" },
  R8:  { id: "R8",  authors: "Depommier C, et al.",      year: 2019, journal: "Nature Medicine",                  title: "Supplementation with Akkermansia muciniphila in overweight and obese human volunteers: a proof-of-concept exploratory study",            doi: "10.1038/s41591-019-0495-2",           if: "82.9", q: "Q1" },
  R9:  { id: "R9",  authors: "Borgeraas H, et al.",      year: 2018, journal: "Obesity Reviews",                  title: "Effects of probiotics on body weight, BMI, fat mass and fat percentage in subjects with overweight or obesity: a systematic review",        doi: "10.1111/obr.12626",                   if: "10.5", q: "Q1" },
  R10: { id: "R10", authors: "Kadooka Y, et al.",        year: 2010, journal: "European Journal of Clinical Nutrition", title: "Regulation of abdominal adiposity by probiotics (Lactobacillus gasseri SBT2055) in adults with obese tendencies in a RCT",      doi: "10.1038/ejcn.2010.19",                if: "4.6",  q: "Q1" },
  R11: { id: "R11", authors: "Liu R, et al.",            year: 2017, journal: "Cell Metabolism",                  title: "Gut microbiome and serum metabolome alterations in obesity and after weight-loss intervention",                                            doi: "10.1016/j.cmet.2017.01.003",          if: "29.0", q: "Q1" },
  R12: { id: "R12", authors: "Cani PD, et al.",          year: 2007, journal: "Diabetes",                         title: "Metabolic endotoxemia initiates obesity and insulin resistance",                                                                           doi: "10.2337/db06-1491",                   if: "8.7",  q: "Q1" },
  R13: { id: "R13", authors: "De Vadder F, et al.",      year: 2014, journal: "Cell",                             title: "Microbiota-generated metabolites promote metabolic benefits via gut-brain neural circuits",                                                  doi: "10.1016/j.cell.2013.12.016",          if: "64.5", q: "Q1" },
  R14: { id: "R14", authors: "Baothman OA, et al.",      year: 2016, journal: "Gut Microbes",                     title: "The role of gut microbiota in the development of obesity and diabetes",                                                                     doi: "10.1080/19490976.2016.1153362",       if: "9.4",  q: "Q1" },
  R15: { id: "R15", authors: "Kumar R, et al.",          year: 2022, journal: "npj Biofilms and Microbiomes",     title: "Identification of gut microbiome predictors of treatment response in patients with ulcerative colitis using machine learning",               doi: "10.1038/s41522-022-00341-3",          if: "10.2", q: "Q1" },
  R16: { id: "R16", authors: "Deleu S, et al.",          year: 2021, journal: "Gut",                              title: "Fecal microbial transplantation in short-chain fatty acid ratio drives engraftment and inflammation resolution",                              doi: "10.1136/gutjnl-2020-323413",          if: "24.5", q: "Q1" },
  R17: { id: "R17", authors: "Parks BW, et al.",         year: 2013, journal: "Cell Metabolism",                  title: "Genetic control of obesity and gut microbiota composition in response to high-fat, high-sucrose diet in mice",                              doi: "10.1016/j.cmet.2012.12.007",          if: "29.0", q: "Q1" },
  R18: { id: "R18", authors: "Guo Y, et al.",            year: 2023, journal: "Nature Aging",                     title: "Metabolomics-based machine learning prediction of healthy aging",                                                                          doi: "10.1038/s43587-023-00398-1",          if: "16.6", q: "Q1" },
  R19: { id: "R19", authors: "Zeevi D, et al.",          year: 2015, journal: "Cell",                             title: "Personalized nutrition by prediction of glycemic responses",                                                                               doi: "10.1016/j.cell.2015.11.001",          if: "64.5", q: "Q1" },
  R20: { id: "R20", authors: "Munoz-Garach A, et al.",   year: 2016, journal: "Nutrients",                        title: "Gut microbiota markers associated with obesity and overweight in a spanish mediterranean population",                                        doi: "10.3390/nu8110680",                   if: "5.9",  q: "Q1" },
};

export default refs;
